// src/app/layout.tsx

import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Geist, Geist_Mono } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import ThemeRegistry from '@/components/shared/ThemeToggle/ThemeRegistry';
import './globals.css';

const geistSans = Geist({
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-geist-sans',
  subsets: ['latin'],
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <title>Next.js 16 Starter Template</title>
        <meta name='description' content={metadata.description as string} />
        <meta name='keywords' content='SEO Words' />
        <meta name='author' content='organizationName' />
        <meta name='robots' content='index, follow' />
        <meta property='og:title' content='organizationName' />
        <script
          type='application/ld+json'
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'Organization',
              name: 'organizationName',
              url: 'url', // e.g: https://ticetedu.com
              logo: 'url', // e.g: https://ticetedu.com/public/ticet-small.svg
              sameAs: [
                'url', // e.g: https://www.facebook.com/ticetedu
                'url', // e.g: https://twitter.com/ticetedu
                'url', // e.g: https://linkedin.com/company/ticet-edu
              ],
            }),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeRegistry>{children}</ThemeRegistry>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
